# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream-python-sdk
from satstream-python-sdk.models.github_com_satstream_ss_utils_rpc_utxo_rune import GithubComSatstreamSsUtilsRpcUtxoRune  # noqa: E501
from satstream-python-sdk.rest import ApiException


class TestGithubComSatstreamSsUtilsRpcUtxoRune(unittest.TestCase):
    """GithubComSatstreamSsUtilsRpcUtxoRune unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComSatstreamSsUtilsRpcUtxoRune(self):
        """Test GithubComSatstreamSsUtilsRpcUtxoRune"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream-python-sdk.models.github_com_satstream_ss_utils_rpc_utxo_rune.GithubComSatstreamSsUtilsRpcUtxoRune()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
