# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.api.runes_api import RunesApi  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestRunesApi(unittest.TestCase):
    """RunesApi unit test stubs"""

    def setUp(self):
        self.api = RunesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_latest_runes(self):
        """Test case for get_latest_runes

        Get latest runes  # noqa: E501
        """
        pass

    def test_get_latest_runes_page(self):
        """Test case for get_latest_runes_page

        Get latest runes page  # noqa: E501
        """
        pass

    def test_get_rune(self):
        """Test case for get_rune

        Get rune info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
