# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.models.responses_get_raw_mempool_response import ResponsesGetRawMempoolResponse  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestResponsesGetRawMempoolResponse(unittest.TestCase):
    """ResponsesGetRawMempoolResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponsesGetRawMempoolResponse(self):
        """Test ResponsesGetRawMempoolResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream_python_sdk.models.responses_get_raw_mempool_response.ResponsesGetRawMempoolResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
