# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.models.all_ofresponses_decode_script_response_data import AllOfresponsesDecodeScriptResponseData  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestAllOfresponsesDecodeScriptResponseData(unittest.TestCase):
    """AllOfresponsesDecodeScriptResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfresponsesDecodeScriptResponseData(self):
        """Test AllOfresponsesDecodeScriptResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream_python_sdk.models.all_ofresponses_decode_script_response_data.AllOfresponsesDecodeScriptResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
