# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.models.github_com_satstream_ss_api_server_api_rune_responses_runes_list_response import GithubComSatstreamSsApiServerApiRuneResponsesRunesListResponse  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestGithubComSatstreamSsApiServerApiRuneResponsesRunesListResponse(unittest.TestCase):
    """GithubComSatstreamSsApiServerApiRuneResponsesRunesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComSatstreamSsApiServerApiRuneResponsesRunesListResponse(self):
        """Test GithubComSatstreamSsApiServerApiRuneResponsesRunesListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream_python_sdk.models.github_com_satstream_ss_api_server_api_rune_responses_runes_list_response.GithubComSatstreamSsApiServerApiRuneResponsesRunesListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
