# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.models.github_com_satstream_ss_utils_bitcoin_cli_btc_tx3 import GithubComSatstreamSsUtilsBitcoinCliBtcTx3  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestGithubComSatstreamSsUtilsBitcoinCliBtcTx3(unittest.TestCase):
    """GithubComSatstreamSsUtilsBitcoinCliBtcTx3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComSatstreamSsUtilsBitcoinCliBtcTx3(self):
        """Test GithubComSatstreamSsUtilsBitcoinCliBtcTx3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream_python_sdk.models.github_com_satstream_ss_utils_bitcoin_cli_btc_tx3.GithubComSatstreamSsUtilsBitcoinCliBtcTx3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
