# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.models.all_ofresponses_get_tx_out_set_info_response_data import AllOfresponsesGetTxOutSetInfoResponseData  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestAllOfresponsesGetTxOutSetInfoResponseData(unittest.TestCase):
    """AllOfresponsesGetTxOutSetInfoResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfresponsesGetTxOutSetInfoResponseData(self):
        """Test AllOfresponsesGetTxOutSetInfoResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream_python_sdk.models.all_ofresponses_get_tx_out_set_info_response_data.AllOfresponsesGetTxOutSetInfoResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
