# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.models.all_ofgithub_com_satstream_ss_utils_bitcoin_cli_decoded_psbt_input_non_witness_utxo import AllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPSBTInputNonWitnessUtxo  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestAllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPSBTInputNonWitnessUtxo(unittest.TestCase):
    """AllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPSBTInputNonWitnessUtxo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPSBTInputNonWitnessUtxo(self):
        """Test AllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPSBTInputNonWitnessUtxo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream_python_sdk.models.all_ofgithub_com_satstream_ss_utils_bitcoin_cli_decoded_psbt_input_non_witness_utxo.AllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPSBTInputNonWitnessUtxo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
