# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.api.mining_api import MiningApi  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestMiningApi(unittest.TestCase):
    """MiningApi unit test stubs"""

    def setUp(self):
        self.api = MiningApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_mining_info(self):
        """Test case for get_mining_info

        Get mining information  # noqa: E501
        """
        pass

    def test_get_network_hashps(self):
        """Test case for get_network_hashps

        Get network hash per second  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
