# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream_python_sdk
from satstream_python_sdk.models.responses_get_mining_info_response import ResponsesGetMiningInfoResponse  # noqa: E501
from satstream_python_sdk.rest import ApiException


class TestResponsesGetMiningInfoResponse(unittest.TestCase):
    """ResponsesGetMiningInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponsesGetMiningInfoResponse(self):
        """Test ResponsesGetMiningInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream_python_sdk.models.responses_get_mining_info_response.ResponsesGetMiningInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
