# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream-python-sdk
from satstream-python-sdk.models.responses_get_address_rune_balance import ResponsesGetAddressRuneBalance  # noqa: E501
from satstream-python-sdk.rest import ApiException


class TestResponsesGetAddressRuneBalance(unittest.TestCase):
    """ResponsesGetAddressRuneBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponsesGetAddressRuneBalance(self):
        """Test ResponsesGetAddressRuneBalance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream-python-sdk.models.responses_get_address_rune_balance.ResponsesGetAddressRuneBalance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
