# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import satstream-python-sdk
from satstream-python-sdk.models.responses_get_block_height_data import ResponsesGetBlockHeightData  # noqa: E501
from satstream-python-sdk.rest import ApiException


class TestResponsesGetBlockHeightData(unittest.TestCase):
    """ResponsesGetBlockHeightData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponsesGetBlockHeightData(self):
        """Test ResponsesGetBlockHeightData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = satstream-python-sdk.models.responses_get_block_height_data.ResponsesGetBlockHeightData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
