# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.responses_get_address_balance import ResponsesGetAddressBalance  # noqa: E501
from swagger_client.rest import ApiException


class TestResponsesGetAddressBalance(unittest.TestCase):
    """ResponsesGetAddressBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponsesGetAddressBalance(self):
        """Test ResponsesGetAddressBalance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.responses_get_address_balance.ResponsesGetAddressBalance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
