# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponsesGetAddressRuneBalanceData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'str',
        'divisibility': 'int',
        'rune': 'str',
        'runeid': 'str',
        'spaced_amount': 'str',
        'spaced_rune': 'str',
        'symbol': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'divisibility': 'divisibility',
        'rune': 'rune',
        'runeid': 'runeid',
        'spaced_amount': 'spacedAmount',
        'spaced_rune': 'spacedRune',
        'symbol': 'symbol'
    }

    def __init__(self, amount=None, divisibility=None, rune=None, runeid=None, spaced_amount=None, spaced_rune=None, symbol=None):  # noqa: E501
        """ResponsesGetAddressRuneBalanceData - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._divisibility = None
        self._rune = None
        self._runeid = None
        self._spaced_amount = None
        self._spaced_rune = None
        self._symbol = None
        self.discriminator = None
        if amount is not None:
            self.amount = amount
        if divisibility is not None:
            self.divisibility = divisibility
        if rune is not None:
            self.rune = rune
        if runeid is not None:
            self.runeid = runeid
        if spaced_amount is not None:
            self.spaced_amount = spaced_amount
        if spaced_rune is not None:
            self.spaced_rune = spaced_rune
        if symbol is not None:
            self.symbol = symbol

    @property
    def amount(self):
        """Gets the amount of this ResponsesGetAddressRuneBalanceData.  # noqa: E501


        :return: The amount of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ResponsesGetAddressRuneBalanceData.


        :param amount: The amount of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def divisibility(self):
        """Gets the divisibility of this ResponsesGetAddressRuneBalanceData.  # noqa: E501


        :return: The divisibility of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :rtype: int
        """
        return self._divisibility

    @divisibility.setter
    def divisibility(self, divisibility):
        """Sets the divisibility of this ResponsesGetAddressRuneBalanceData.


        :param divisibility: The divisibility of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :type: int
        """

        self._divisibility = divisibility

    @property
    def rune(self):
        """Gets the rune of this ResponsesGetAddressRuneBalanceData.  # noqa: E501


        :return: The rune of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :rtype: str
        """
        return self._rune

    @rune.setter
    def rune(self, rune):
        """Sets the rune of this ResponsesGetAddressRuneBalanceData.


        :param rune: The rune of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :type: str
        """

        self._rune = rune

    @property
    def runeid(self):
        """Gets the runeid of this ResponsesGetAddressRuneBalanceData.  # noqa: E501


        :return: The runeid of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :rtype: str
        """
        return self._runeid

    @runeid.setter
    def runeid(self, runeid):
        """Sets the runeid of this ResponsesGetAddressRuneBalanceData.


        :param runeid: The runeid of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :type: str
        """

        self._runeid = runeid

    @property
    def spaced_amount(self):
        """Gets the spaced_amount of this ResponsesGetAddressRuneBalanceData.  # noqa: E501


        :return: The spaced_amount of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :rtype: str
        """
        return self._spaced_amount

    @spaced_amount.setter
    def spaced_amount(self, spaced_amount):
        """Sets the spaced_amount of this ResponsesGetAddressRuneBalanceData.


        :param spaced_amount: The spaced_amount of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :type: str
        """

        self._spaced_amount = spaced_amount

    @property
    def spaced_rune(self):
        """Gets the spaced_rune of this ResponsesGetAddressRuneBalanceData.  # noqa: E501


        :return: The spaced_rune of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :rtype: str
        """
        return self._spaced_rune

    @spaced_rune.setter
    def spaced_rune(self, spaced_rune):
        """Sets the spaced_rune of this ResponsesGetAddressRuneBalanceData.


        :param spaced_rune: The spaced_rune of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :type: str
        """

        self._spaced_rune = spaced_rune

    @property
    def symbol(self):
        """Gets the symbol of this ResponsesGetAddressRuneBalanceData.  # noqa: E501


        :return: The symbol of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this ResponsesGetAddressRuneBalanceData.


        :param symbol: The symbol of this ResponsesGetAddressRuneBalanceData.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponsesGetAddressRuneBalanceData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponsesGetAddressRuneBalanceData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
