# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnalyzePSBTRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'psbt': 'str'
    }

    attribute_map = {
        'psbt': 'psbt'
    }

    def __init__(self, psbt=None):  # noqa: E501
        """AnalyzePSBTRequest - a model defined in Swagger"""  # noqa: E501
        self._psbt = None
        self.discriminator = None
        if psbt is not None:
            self.psbt = psbt

    @property
    def psbt(self):
        """Gets the psbt of this AnalyzePSBTRequest.  # noqa: E501

        The base64-encoded PSBT to analyze  # noqa: E501

        :return: The psbt of this AnalyzePSBTRequest.  # noqa: E501
        :rtype: str
        """
        return self._psbt

    @psbt.setter
    def psbt(self, psbt):
        """Sets the psbt of this AnalyzePSBTRequest.

        The base64-encoded PSBT to analyze  # noqa: E501

        :param psbt: The psbt of this AnalyzePSBTRequest.  # noqa: E501
        :type: str
        """

        self._psbt = psbt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnalyzePSBTRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalyzePSBTRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
