# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Duration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nanos': 'int',
        'secs': 'int'
    }

    attribute_map = {
        'nanos': 'nanos',
        'secs': 'secs'
    }

    def __init__(self, nanos=None, secs=None):  # noqa: E501
        """Duration - a model defined in Swagger"""  # noqa: E501
        self._nanos = None
        self._secs = None
        self.discriminator = None
        if nanos is not None:
            self.nanos = nanos
        if secs is not None:
            self.secs = secs

    @property
    def nanos(self):
        """Gets the nanos of this Duration.  # noqa: E501


        :return: The nanos of this Duration.  # noqa: E501
        :rtype: int
        """
        return self._nanos

    @nanos.setter
    def nanos(self, nanos):
        """Sets the nanos of this Duration.


        :param nanos: The nanos of this Duration.  # noqa: E501
        :type: int
        """

        self._nanos = nanos

    @property
    def secs(self):
        """Gets the secs of this Duration.  # noqa: E501


        :return: The secs of this Duration.  # noqa: E501
        :rtype: int
        """
        return self._secs

    @secs.setter
    def secs(self, secs):
        """Sets the secs of this Duration.


        :param secs: The secs of this Duration.  # noqa: E501
        :type: int
        """

        self._secs = secs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Duration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Duration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
