# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GithubComSatstreamSsUtilsRpcPrevOut(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'height': 'int',
        'n': 'int',
        'populated': 'bool',
        'rune_holdings': 'list[GithubComSatstreamSsUtilsRpcUtxoRune]',
        'script_pub_key': 'GithubComSatstreamSsUtilsRpcScriptPubKey',
        'value': 'float'
    }

    attribute_map = {
        'height': 'height',
        'n': 'n',
        'populated': 'populated',
        'rune_holdings': 'rune_holdings',
        'script_pub_key': 'scriptPubKey',
        'value': 'value'
    }

    def __init__(self, height=None, n=None, populated=None, rune_holdings=None, script_pub_key=None, value=None):  # noqa: E501
        """GithubComSatstreamSsUtilsRpcPrevOut - a model defined in Swagger"""  # noqa: E501
        self._height = None
        self._n = None
        self._populated = None
        self._rune_holdings = None
        self._script_pub_key = None
        self._value = None
        self.discriminator = None
        if height is not None:
            self.height = height
        if n is not None:
            self.n = n
        if populated is not None:
            self.populated = populated
        if rune_holdings is not None:
            self.rune_holdings = rune_holdings
        if script_pub_key is not None:
            self.script_pub_key = script_pub_key
        if value is not None:
            self.value = value

    @property
    def height(self):
        """Gets the height of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501


        :return: The height of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this GithubComSatstreamSsUtilsRpcPrevOut.


        :param height: The height of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def n(self):
        """Gets the n of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501


        :return: The n of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :rtype: int
        """
        return self._n

    @n.setter
    def n(self, n):
        """Sets the n of this GithubComSatstreamSsUtilsRpcPrevOut.


        :param n: The n of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :type: int
        """

        self._n = n

    @property
    def populated(self):
        """Gets the populated of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501

        * The populated field is used to determine if the prevout has been populated from our code or automatically by the RPC on fetch  # noqa: E501

        :return: The populated of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :rtype: bool
        """
        return self._populated

    @populated.setter
    def populated(self, populated):
        """Sets the populated of this GithubComSatstreamSsUtilsRpcPrevOut.

        * The populated field is used to determine if the prevout has been populated from our code or automatically by the RPC on fetch  # noqa: E501

        :param populated: The populated of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :type: bool
        """

        self._populated = populated

    @property
    def rune_holdings(self):
        """Gets the rune_holdings of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501


        :return: The rune_holdings of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :rtype: list[GithubComSatstreamSsUtilsRpcUtxoRune]
        """
        return self._rune_holdings

    @rune_holdings.setter
    def rune_holdings(self, rune_holdings):
        """Sets the rune_holdings of this GithubComSatstreamSsUtilsRpcPrevOut.


        :param rune_holdings: The rune_holdings of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :type: list[GithubComSatstreamSsUtilsRpcUtxoRune]
        """

        self._rune_holdings = rune_holdings

    @property
    def script_pub_key(self):
        """Gets the script_pub_key of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501


        :return: The script_pub_key of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :rtype: GithubComSatstreamSsUtilsRpcScriptPubKey
        """
        return self._script_pub_key

    @script_pub_key.setter
    def script_pub_key(self, script_pub_key):
        """Sets the script_pub_key of this GithubComSatstreamSsUtilsRpcPrevOut.


        :param script_pub_key: The script_pub_key of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :type: GithubComSatstreamSsUtilsRpcScriptPubKey
        """

        self._script_pub_key = script_pub_key

    @property
    def value(self):
        """Gets the value of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501


        :return: The value of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this GithubComSatstreamSsUtilsRpcPrevOut.


        :param value: The value of this GithubComSatstreamSsUtilsRpcPrevOut.  # noqa: E501
        :type: float
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GithubComSatstreamSsUtilsRpcPrevOut, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GithubComSatstreamSsUtilsRpcPrevOut):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
