# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entries': 'list[GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry]',
        'more': 'bool',
        'next': 'int',
        'prev': 'int'
    }

    attribute_map = {
        'entries': 'entries',
        'more': 'more',
        'next': 'next',
        'prev': 'prev'
    }

    def __init__(self, entries=None, more=None, next=None, prev=None):  # noqa: E501
        """GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse - a model defined in Swagger"""  # noqa: E501
        self._entries = None
        self._more = None
        self._next = None
        self._prev = None
        self.discriminator = None
        if entries is not None:
            self.entries = entries
        if more is not None:
            self.more = more
        if next is not None:
            self.next = next
        if prev is not None:
            self.prev = prev

    @property
    def entries(self):
        """Gets the entries of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501


        :return: The entries of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :rtype: list[GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.


        :param entries: The entries of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :type: list[GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry]
        """

        self._entries = entries

    @property
    def more(self):
        """Gets the more of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501


        :return: The more of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :rtype: bool
        """
        return self._more

    @more.setter
    def more(self, more):
        """Sets the more of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.


        :param more: The more of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :type: bool
        """

        self._more = more

    @property
    def next(self):
        """Gets the next of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501


        :return: The next of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :rtype: int
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.


        :param next: The next of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :type: int
        """

        self._next = next

    @property
    def prev(self):
        """Gets the prev of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501


        :return: The prev of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :rtype: int
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.


        :param prev: The prev of this GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse.  # noqa: E501
        :type: int
        """

        self._prev = prev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
