# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LatestInscriptionsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ids': 'list[str]',
        'more': 'bool',
        'page_index': 'int'
    }

    attribute_map = {
        'ids': 'ids',
        'more': 'more',
        'page_index': 'page_index'
    }

    def __init__(self, ids=None, more=None, page_index=None):  # noqa: E501
        """LatestInscriptionsResponse - a model defined in Swagger"""  # noqa: E501
        self._ids = None
        self._more = None
        self._page_index = None
        self.discriminator = None
        if ids is not None:
            self.ids = ids
        if more is not None:
            self.more = more
        if page_index is not None:
            self.page_index = page_index

    @property
    def ids(self):
        """Gets the ids of this LatestInscriptionsResponse.  # noqa: E501


        :return: The ids of this LatestInscriptionsResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._ids

    @ids.setter
    def ids(self, ids):
        """Sets the ids of this LatestInscriptionsResponse.


        :param ids: The ids of this LatestInscriptionsResponse.  # noqa: E501
        :type: list[str]
        """

        self._ids = ids

    @property
    def more(self):
        """Gets the more of this LatestInscriptionsResponse.  # noqa: E501


        :return: The more of this LatestInscriptionsResponse.  # noqa: E501
        :rtype: bool
        """
        return self._more

    @more.setter
    def more(self, more):
        """Sets the more of this LatestInscriptionsResponse.


        :param more: The more of this LatestInscriptionsResponse.  # noqa: E501
        :type: bool
        """

        self._more = more

    @property
    def page_index(self):
        """Gets the page_index of this LatestInscriptionsResponse.  # noqa: E501


        :return: The page_index of this LatestInscriptionsResponse.  # noqa: E501
        :rtype: int
        """
        return self._page_index

    @page_index.setter
    def page_index(self, page_index):
        """Sets the page_index of this LatestInscriptionsResponse.


        :param page_index: The page_index of this LatestInscriptionsResponse.  # noqa: E501
        :type: int
        """

        self._page_index = page_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LatestInscriptionsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LatestInscriptionsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
