# coding: utf-8

"""
    Satstream API

    Satstream API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: team@satstream.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScriptPubKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'asm': 'str',
        'desc': 'str',
        'hex': 'str',
        'type': 'str'
    }

    attribute_map = {
        'address': 'address',
        'asm': 'asm',
        'desc': 'desc',
        'hex': 'hex',
        'type': 'type'
    }

    def __init__(self, address=None, asm=None, desc=None, hex=None, type=None):  # noqa: E501
        """ScriptPubKey - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._asm = None
        self._desc = None
        self._hex = None
        self._type = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if asm is not None:
            self.asm = asm
        if desc is not None:
            self.desc = desc
        if hex is not None:
            self.hex = hex
        if type is not None:
            self.type = type

    @property
    def address(self):
        """Gets the address of this ScriptPubKey.  # noqa: E501


        :return: The address of this ScriptPubKey.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ScriptPubKey.


        :param address: The address of this ScriptPubKey.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def asm(self):
        """Gets the asm of this ScriptPubKey.  # noqa: E501


        :return: The asm of this ScriptPubKey.  # noqa: E501
        :rtype: str
        """
        return self._asm

    @asm.setter
    def asm(self, asm):
        """Sets the asm of this ScriptPubKey.


        :param asm: The asm of this ScriptPubKey.  # noqa: E501
        :type: str
        """

        self._asm = asm

    @property
    def desc(self):
        """Gets the desc of this ScriptPubKey.  # noqa: E501


        :return: The desc of this ScriptPubKey.  # noqa: E501
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc):
        """Sets the desc of this ScriptPubKey.


        :param desc: The desc of this ScriptPubKey.  # noqa: E501
        :type: str
        """

        self._desc = desc

    @property
    def hex(self):
        """Gets the hex of this ScriptPubKey.  # noqa: E501


        :return: The hex of this ScriptPubKey.  # noqa: E501
        :rtype: str
        """
        return self._hex

    @hex.setter
    def hex(self, hex):
        """Sets the hex of this ScriptPubKey.


        :param hex: The hex of this ScriptPubKey.  # noqa: E501
        :type: str
        """

        self._hex = hex

    @property
    def type(self):
        """Gets the type of this ScriptPubKey.  # noqa: E501


        :return: The type of this ScriptPubKey.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ScriptPubKey.


        :param type: The type of this ScriptPubKey.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScriptPubKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScriptPubKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
